// <auto-generated />
using System;
using BookingSystem.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingSystem.Persistence.Migrations
{
    [DbContext(typeof(BookingSystemDbContext))]
    [Migration("20240918150345_bite")]
    partial class bite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingSystem.Domain.Entities.Amenities.Amenity", b =>
                {
                    b.Property<Guid>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AmenityCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ConferenceRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AmenityId");

                    b.HasIndex("AmenityCategoryId");

                    b.HasIndex("ConferenceRoomId");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Amenities.AmenityCategory", b =>
                {
                    b.Property<Guid>("AmenityCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AmenityCategoryId");

                    b.ToTable("AmenityCategories");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Bookings.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookingNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingNumber"));

                    b.Property<Guid>("ConferenceRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingId");

                    b.HasIndex("ConferenceRoomId");

                    b.HasIndex("EventId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a1ee9"),
                            BookingNumber = 0,
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee7"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("ee98f549-e190-5e9f-aa15-18c2292a2ee1"),
                            Status = "Pending"
                        },
                        new
                        {
                            BookingId = new Guid("ee28f549-e790-5e9f-aa15-18c2292a2ee2"),
                            BookingNumber = 0,
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee8"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("ee98f549-e190-5e9f-aa15-18c2292a2ee1"),
                            Status = "Pending"
                        },
                        new
                        {
                            BookingId = new Guid("ee38f549-e790-5e9f-aa15-18c2292a2ee3"),
                            BookingNumber = 0,
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("ee98f549-e190-5e9f-aa15-18c2292a2ee1"),
                            Status = "Pending"
                        },
                        new
                        {
                            BookingId = new Guid("ee08f549-e790-5e9f-aa15-18c2292a2ee4"),
                            BookingNumber = 0,
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee0"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("ee98f549-e190-5e9f-aa15-18c2292a2ee1"),
                            Status = "Cancelled"
                        },
                        new
                        {
                            BookingId = new Guid("ee48f549-e790-5e9f-aa15-18c2292a2ee5"),
                            BookingNumber = 0,
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee1"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("ee98f549-e190-5e9f-aa15-18c2292a2ee1"),
                            Status = "Pending"
                        },
                        new
                        {
                            BookingId = new Guid("ee58f549-e790-5e9f-aa15-18c2292a2ee6"),
                            BookingNumber = 0,
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee2"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("ee98f549-e190-5e9f-aa15-18c2292a2ee1"),
                            Status = "Approved"
                        },
                        new
                        {
                            BookingId = new Guid("ee68f549-e790-5e9f-aa15-18c2292a2ee7"),
                            BookingNumber = 0,
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("ee98f549-e190-5e9f-aa15-18c2292a2ee1"),
                            Status = "Cancelled"
                        },
                        new
                        {
                            BookingId = new Guid("ee78f549-e790-5e9f-aa15-18c2292a2ee8"),
                            BookingNumber = 0,
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee4"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("ee98f549-e190-5e9f-aa15-18c2292a2ee1"),
                            Status = "Approved"
                        },
                        new
                        {
                            BookingId = new Guid("ee88f549-e790-5e9f-aa15-18c2292a2ee9"),
                            BookingNumber = 0,
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee5"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("ee98f549-e190-5e9f-aa15-18c2292a2ee1"),
                            Status = "Pending"
                        },
                        new
                        {
                            BookingId = new Guid("ee91f549-e790-5e9f-aa15-18c2292a1ee9"),
                            BookingNumber = 0,
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee6"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = new Guid("ee98f549-e190-5e9f-aa15-18c2292a2ee1"),
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.ConferenceRooms.ConferenceRoom", b =>
                {
                    b.Property<Guid>("ConferenceRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConferenceRoomId");

                    b.ToTable("ConferenceRooms");

                    b.HasData(
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a1ee1"),
                            Capacity = 10,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 1 Description",
                            IsAvailable = true,
                            Name = "Conference Room 1",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee2"),
                            Capacity = 20,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 2 Description",
                            IsAvailable = true,
                            Name = "Conference Room 2",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee3"),
                            Capacity = 30,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 3 Description",
                            IsAvailable = true,
                            Name = "Conference Room 3",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee4"),
                            Capacity = 40,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 4 Description",
                            IsAvailable = true,
                            Name = "Conference Room 4",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee5"),
                            Capacity = 50,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 5 Description",
                            IsAvailable = true,
                            Name = "Conference Room 5",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee6"),
                            Capacity = 60,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 6 Description",
                            IsAvailable = true,
                            Name = "Conference Room 6",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee7"),
                            Capacity = 70,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 7 Description",
                            IsAvailable = true,
                            Name = "Conference Room 7",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee8"),
                            Capacity = 80,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 8 Description",
                            IsAvailable = true,
                            Name = "Conference Room 8",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee9"),
                            Capacity = 90,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 9 Description",
                            IsAvailable = true,
                            Name = "Conference Room 9",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-18c2292a2ee0"),
                            Capacity = 100,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 10 Description",
                            IsAvailable = true,
                            Name = "Conference Room 10",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee0"),
                            Capacity = 110,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 11 Description",
                            IsAvailable = true,
                            Name = "Conference Room 11",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee1"),
                            Capacity = 120,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 12 Description",
                            IsAvailable = true,
                            Name = "Conference Room 12",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee2"),
                            Capacity = 130,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 13 Description",
                            IsAvailable = true,
                            Name = "Conference Room 13",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee3"),
                            Capacity = 140,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 14 Description",
                            IsAvailable = true,
                            Name = "Conference Room 14",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee4"),
                            Capacity = 150,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 15 Description",
                            IsAvailable = true,
                            Name = "Conference Room 15",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee5"),
                            Capacity = 160,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 16 Description",
                            IsAvailable = true,
                            Name = "Conference Room 16",
                            Tags = ""
                        },
                        new
                        {
                            ConferenceRoomId = new Guid("ee98f549-e790-5e9f-aa15-11c2292a1ee6"),
                            Capacity = 170,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference Room 17 Description",
                            IsAvailable = true,
                            Name = "Conference Room 17",
                            Tags = ""
                        });
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Consumables.Consumable", b =>
                {
                    b.Property<Guid>("ConsumableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsumableCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsumableId");

                    b.HasIndex("ConsumableCategoryId");

                    b.ToTable("Consumables");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Consumables.ConsumableCategory", b =>
                {
                    b.Property<Guid>("ConsumableCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountOfConsumables")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsumableCategoryId");

                    b.ToTable("ConsumableCategories");

                    b.HasData(
                        new
                        {
                            ConsumableCategoryId = new Guid("ee48f549-e790-5e9f-aa15-18c2292a2ee9"),
                            AmountOfConsumables = 0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Name = "Markers"
                        },
                        new
                        {
                            ConsumableCategoryId = new Guid("ee58f549-e790-5e9f-aa15-18c2292a2ee9"),
                            AmountOfConsumables = 0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Name = "Pens"
                        });
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Events.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("ee98f549-e110-5e9f-aa15-18c2292a2ee1"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Class, Training or Workshop"
                        },
                        new
                        {
                            CategoryId = new Guid("ee98f549-e120-5e9f-aa15-18c2292a2ee2"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Conference"
                        },
                        new
                        {
                            CategoryId = new Guid("ee98f549-e130-5e9f-aa15-18c2292a2ee3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Meeting"
                        },
                        new
                        {
                            CategoryId = new Guid("ee98f549-e140-5e9f-aa15-18c2292a2ee4"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Convention"
                        },
                        new
                        {
                            CategoryId = new Guid("ee98f549-e150-5e9f-aa15-18c2292a2ee5"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dinner or Gala"
                        });
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Events.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("ee98f549-e190-5e9f-aa15-18c2292a2ee1"),
                            CategoryId = new Guid("ee98f549-e150-5e9f-aa15-18c2292a2ee5"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference 1 Description",
                            End = new DateTime(2024, 9, 23, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "primary",
                            Start = new DateTime(2024, 9, 23, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Conference 1"
                        },
                        new
                        {
                            EventId = new Guid("ee11f549-e190-5e9f-aa15-18c2292a2ee1"),
                            CategoryId = new Guid("ee98f549-e150-5e9f-aa15-18c2292a2ee5"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conference 1 copy Description",
                            End = new DateTime(2024, 9, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "primary",
                            Start = new DateTime(2024, 9, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Conference 1 Copy"
                        },
                        new
                        {
                            EventId = new Guid("ee98f540-e790-5e9f-aa15-18c2292a2ee2"),
                            CategoryId = new Guid("ee98f549-e150-5e9f-aa15-18c2292a2ee5"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            End = new DateTime(2024, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "primary",
                            Start = new DateTime(2024, 9, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Conference 2"
                        },
                        new
                        {
                            EventId = new Guid("ee98f548-e790-5e9f-aa15-18c2292a2ee3"),
                            CategoryId = new Guid("ee98f549-e150-5e9f-aa15-18c2292a2ee5"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            End = new DateTime(2024, 9, 24, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "primary",
                            Start = new DateTime(2024, 9, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Conference 3"
                        },
                        new
                        {
                            EventId = new Guid("ee98f547-e790-5e9f-aa15-18c2292a2ee4"),
                            CategoryId = new Guid("ee98f549-e140-5e9f-aa15-18c2292a2ee4"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            End = new DateTime(2024, 9, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "warning",
                            Start = new DateTime(2024, 9, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Conference 4"
                        },
                        new
                        {
                            EventId = new Guid("ee98f546-e790-5e9f-aa15-18c2292a2ee5"),
                            CategoryId = new Guid("ee98f549-e140-5e9f-aa15-18c2292a2ee4"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            End = new DateTime(2024, 9, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "warning",
                            Start = new DateTime(2024, 9, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Conference 5"
                        },
                        new
                        {
                            EventId = new Guid("ee98f545-e790-5e9f-aa15-18c2292a2ee6"),
                            CategoryId = new Guid("ee98f549-e130-5e9f-aa15-18c2292a2ee3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            End = new DateTime(2024, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "warning",
                            Start = new DateTime(2024, 9, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Conference 6"
                        },
                        new
                        {
                            EventId = new Guid("ee98f544-e790-5e9f-aa15-18c1292a2ee7"),
                            CategoryId = new Guid("ee98f549-e130-5e9f-aa15-18c2292a2ee3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            End = new DateTime(2024, 9, 25, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "warning",
                            Start = new DateTime(2024, 9, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Conference 7"
                        },
                        new
                        {
                            EventId = new Guid("ee98f541-e790-5e9f-aa15-18c2292a2ee8"),
                            CategoryId = new Guid("ee98f549-e130-5e9f-aa15-18c2292a2ee3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            End = new DateTime(2024, 9, 26, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "success",
                            Start = new DateTime(2024, 9, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Conference 8"
                        },
                        new
                        {
                            EventId = new Guid("ee98f542-e790-5e9f-aa15-18c2292a2ee9"),
                            CategoryId = new Guid("ee98f549-e130-5e9f-aa15-18c2292a2ee3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            End = new DateTime(2024, 9, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "danger",
                            Start = new DateTime(2024, 9, 26, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Conference 9"
                        },
                        new
                        {
                            EventId = new Guid("ee98f543-e790-5e9f-aa15-18c2292a1ee9"),
                            CategoryId = new Guid("ee98f549-e130-5e9f-aa15-18c2292a2ee3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            End = new DateTime(2024, 9, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Label = "primary",
                            Start = new DateTime(2024, 9, 25, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Conference 10"
                        });
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Inventory.Stock", b =>
                {
                    b.Property<Guid>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Inventory.StockEnquiry", b =>
                {
                    b.Property<Guid>("StockEnquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockEnquiryId");

                    b.HasIndex("BookingId");

                    b.ToTable("StockEnquiries");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Inventory.StockItem", b =>
                {
                    b.Property<Guid>("StockItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConsumableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StockNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockItemId");

                    b.HasIndex("ConsumableId");

                    b.HasIndex("StockId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Inventory.StockItemEnquiry", b =>
                {
                    b.Property<Guid>("StockItemEnquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsumableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("StockEnquiryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StockItemEnquiryId");

                    b.HasIndex("StockEnquiryId");

                    b.ToTable("StockItemEnquiries");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Amenities.Amenity", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Amenities.AmenityCategory", "AmenityCategory")
                        .WithMany("Amenities")
                        .HasForeignKey("AmenityCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingSystem.Domain.Entities.ConferenceRooms.ConferenceRoom", "ConferenceRoom")
                        .WithMany("Amenities")
                        .HasForeignKey("ConferenceRoomId");

                    b.Navigation("AmenityCategory");

                    b.Navigation("ConferenceRoom");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Bookings.Booking", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.ConferenceRooms.ConferenceRoom", "ConferenceRoom")
                        .WithMany()
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingSystem.Domain.Entities.Events.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceRoom");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Consumables.Consumable", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Consumables.ConsumableCategory", "Category")
                        .WithMany("Consumables")
                        .HasForeignKey("ConsumableCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Events.Event", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Events.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Inventory.StockEnquiry", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Bookings.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Inventory.StockItem", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Consumables.Consumable", "Consumable")
                        .WithMany()
                        .HasForeignKey("ConsumableId");

                    b.HasOne("BookingSystem.Domain.Entities.Inventory.Stock", "Stock")
                        .WithMany("StockItems")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumable");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Inventory.StockItemEnquiry", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Inventory.StockEnquiry", "StockEnquiry")
                        .WithMany("StockItemEnquiries")
                        .HasForeignKey("StockEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockEnquiry");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Amenities.AmenityCategory", b =>
                {
                    b.Navigation("Amenities");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.ConferenceRooms.ConferenceRoom", b =>
                {
                    b.Navigation("Amenities");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Consumables.ConsumableCategory", b =>
                {
                    b.Navigation("Consumables");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Events.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Events.Event", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Inventory.Stock", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Inventory.StockEnquiry", b =>
                {
                    b.Navigation("StockItemEnquiries");
                });
#pragma warning restore 612, 618
        }
    }
}
